#!/bin/bash

# Opciones del menú
opcion=$(echo -e " Bloquear\n󰈆 Salir\n Reiniciar\n Apagar" | dmenu -i -p "Bienvenido $USER:")

case "$opcion" in
    " Bloquear")
	dm-tool lock & # o el bloqueador de tu preferencia
	;;
    "󰈆 Salir")
	i3-msg exit
	;;
    " Reiniciar")
        reboot
        ;;
     " Apagar")
        poweroff
	;;
    *)
        # Si se cierra dmenu sin seleccionar nada, no hacer nada
        ;;
esac
